language: python
cache: pip

matrix:
  include:
    - python: "3.7"
    - python: "3.8"

# command to install dependencies
install:
  - pip install -e .[dev]

# command to run pytest
script: pytest -v tests

notifications:
  email: false
